version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Painel de gest√£o
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  service-order:
    build: ./service-order
    container_name: service-order
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      QUEUE_ORDERS: orders
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  service-payment:
    build: ./service-payment
    container_name: service-payment
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      QUEUE_ORDERS: orders
      PORT: 3002
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
